version: '3'
services:
  nodejs-app:
    restart: always
    build: 
      context: .
      target: production
      dockerfile: Dockerfile.node
    depends_on:
      - postgres
    container_name: iut_back_nodejs
    ports:
      - "${NODEJS_PORT}:${NODEJS_PORT}"
      
  postgres:
    image: postgres:latest
    container_name: iut_database
    restart: always
    build: 
      context: .
    env_file:
      - .env
    ports:
      - "5432:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
volumes:
  postgres_data: