version: '3.5'

services:
  postgres:
    build:
      context: .
    container_name: ${PG_CONTAINER_NAME}
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - mynetwork  # Attachez le conteneur PostgreSQL à notre réseau personnalisé.
    restart: always
    command: ["postgres", "-c", "listen_addresses=*"]
networks:
  mynetwork:
    driver: bridge  # Utilisez un réseau de type "bridge" personnalisé.